services:
  nginx:
    image: nginx:alpine
    container_name: local-webserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - web-dev
    networks:
      - webnet

  web-dev:
    image: node:18-alpine
    container_name: web-dev-tools
    working_dir: /app
    volumes:
      - ./src:/app
      - /app/node_modules
    command: tail -f /dev/null  # Keeps container running for development
    networks:
      - webnet
    environment:
      - NODE_ENV=development

networks:
  webnet:
    driver: bridge

volumes:
  node_modules: