apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: brew-detective-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/timeout: "300s"
    spec:
      serviceAccountName: brew-detective@brew-detective.iam.gserviceaccount.com
      containerConcurrency: 100
      containers:
      - image: us-central1-docker.pkg.dev/brew-detective/brew-detective-repo/brew-detective-backend
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "brew-detective"
        - name: FIRESTORE_DATABASE_ID
          value: "brew-detective"
        - name: GOOGLE_CLIENT_ID
          value: "1087966598090-sl8tt327bp6bpfeeb4td1fv2a3chtli5.apps.googleusercontent.com"
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: GOOGLE_REDIRECT_URL
          value: "https://brew-detective-backend-1087966598090.us-central1.run.app/auth/google/callback"
        - name: GIN_MODE
          value: "release"
        - name: FRONTEND_URL
          value: "https://kporras07.github.io/brew-detective"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi